version: "3.7"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=v&64ny@1!bygkq+fx5v_-y=nj3in@5^g)&(5q9%e#)fme1%rs=
      - DEBUG=True
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_8mZ216teiA96kbPpAWmfz6Hz00XFo6tCA6
      - STRIPE_TEST_SECRET_KEY=sk_test_51G4L75Fh1uRkuYPnfuyD9lufIbPKwWgiI6OYi3xS5Wf2HjRDpETJty8pQAi9w8kESFOjdt4jG9MUAThgWgYl1IAS00ZFFIowe0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
