# Generated by Django 3.0.1 on 2020-06-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_rent_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rent_tenant',
            field=models.CharField(blank=True, max_length=10, verbose_name='Rent he/she pays'),
        ),
    ]
