# Generated by Django 3.0.1 on 2020-06-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_rent_tenant'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Contract',
        ),
    ]
