# Generated by Django 3.0.7 on 2020-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20200629_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthly_property_expense_track',
            field=models.BooleanField(default=False),
        ),
    ]
