# Generated by Django 3.0.1 on 2020-06-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_auto_20200620_2357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('country_of_origin', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('is_active', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.Property')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
