# Generated by Django 3.0.1 on 2020-06-21 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_auto_20200620_2357'),
        ('tenants', '0002_auto_20200620_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenants',
            new_name='Tenant',
        ),
    ]
