# Generated by Django 3.0.1 on 2020-06-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20200621_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rent_tenant',
            field=models.CharField(blank=True, max_length=10, verbose_name='Rent he/she pays'),
        ),
    ]
