# Generated by Django 3.0.7 on 2020-07-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_monthlymaintenance_renovationteam_renovationteamexpenses'),
        ('tenants', '0004_tenant_rent_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='apartment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
