# Generated by Django 3.0.7 on 2020-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('role_status', models.CharField(blank=True, choices=[('User', 'User'), ('Staff', 'Staff')], default='User', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Banned', 'Banned'), ('Close', 'Close')], default='User', max_length=100)),
            ],
        ),
    ]
