# Generated by Django 3.0.7 on 2020-07-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='contracts_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_details',
            name='owners_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_details',
            name='properties_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_details',
            name='tenants_permission',
            field=models.BooleanField(default=False),
        ),
    ]
