# Generated by Django 3.0.7 on 2020-07-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0002_auto_20200724_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='role_status',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Organization', 'Organization')], default='User', max_length=100),
        ),
    ]
