# Generated by Django 3.0.7 on 2020-07-24 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0003_auto_20200724_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
