# Generated by Django 3.0.7 on 2020-07-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0004_auto_20200724_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='Company_details',
        ),
    ]
