# Generated by Django 3.0.7 on 2020-07-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0007_company_detail_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_detail',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='company_detail',
            name='verified',
        ),
        migrations.AddField(
            model_name='company_detail',
            name='varified',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
