# Generated by Django 3.0.7 on 2020-07-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creating_user', '0008_auto_20200725_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detail',
            old_name='varified',
            new_name='verified',
        ),
    ]
