# Generated by Django 3.0.1 on 2020-06-20 16:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000, null=True)),
                ('residence_complex', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('street_number', models.IntegerField()),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('entrance', models.CharField(max_length=200, null=True)),
                ('apartament', models.CharField(max_length=200, null=True)),
                ('reper', models.CharField(max_length=200, null=True)),
                ('vecinatati', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(choices=[('birouri', 'Birouri'), ('rezidentaial', 'Rezidential'), ('comercial', 'Comercial')], default='rezidentaial', max_length=20, verbose_name='Destination')),
                ('layout', models.CharField(choices=[('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Nedecomandat'), ('circular', 'Circular'), ('vagon', 'Vagon')], default='decomandat', max_length=20, verbose_name='Layout')),
                ('floor', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('comfort_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('lux', 'Lux')], default='1', max_length=20, verbose_name='Comfort Type')),
                ('interior_state', models.CharField(choices=[('other', 'Other'), ('necesita-renovare', 'Necesita-Renovare'), ('renovat', 'Renovat'), ('nou', 'Nou'), ('caramida', 'Caramida')], default='other', max_length=20, verbose_name='Interior State')),
                ('building_age', models.IntegerField()),
                ('usable_sqm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('build_sqm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('kitchen', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('building_type', models.CharField(choices=[('beton', 'Beton'), ('caramida', 'Caramida'), ('lemn', 'Lemn'), ('bca', 'Bca'), ('metal', 'Metal'), ('other', 'Other')], default='beton', max_length=20, verbose_name='Building Type')),
                ('construction_date', models.DateTimeField(blank=True, null=True)),
                ('construction_type', models.CharField(choices=[('house', 'House'), ('mix-building', 'Mix-Building'), ('studio-building', 'Studio-Building')], default='mix-building', max_length=20, verbose_name='Construction Type')),
                ('basement', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('rent', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_1', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_2', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_3', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_4', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_5', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_6', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_7', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_8', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_9', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_10', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_11', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_12', models.ImageField(blank=True, upload_to='properties/')),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
