# Generated by Django 3.0.1 on 2020-06-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
