# Generated by Django 3.0.1 on 2020-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='property_comment',
            field=models.ManyToManyField(related_name='comments', to='properties.Property'),
        ),
    ]
