# Generated by Django 3.0.1 on 2020-06-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
    ]
