# Generated by Django 3.0.7 on 2020-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageBuying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_costs', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('notary_costs', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('legal_costs', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('accountant_costs', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('other_costs', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('buy_price', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageForRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_rent', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('asking_price', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('residence_complex', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('entrance', models.CharField(max_length=200, null=True)),
                ('floor', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('apartament_number', models.CharField(max_length=200, null=True)),
                ('reper', models.CharField(max_length=200, null=True)),
                ('vecinatati', models.CharField(max_length=200, null=True)),
                ('usable_sqm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('build_sqm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('destination', models.CharField(choices=[('birouri', 'Birouri'), ('rezidentaial', 'Rezidential'), ('comercial', 'Comercial')], default='rezidentaial', max_length=20, verbose_name='Destination')),
                ('layout', models.CharField(choices=[('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Nedecomandat'), ('circular', 'Circular'), ('vagon', 'Vagon')], default='decomandat', max_length=20, verbose_name='Layout')),
                ('comfort_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('lux', 'Lux')], default='1', max_length=20, verbose_name='Comfort Type')),
                ('interior_state', models.CharField(choices=[('other', 'Other'), ('necesita-renovare', 'Necesita-Renovare'), ('renovat', 'Renovat'), ('nou', 'Nou'), ('caramida', 'Caramida')], default='other', max_length=20, verbose_name='Interior State')),
                ('number_of_rooms', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('kitchen', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('building_type', models.CharField(choices=[('beton', 'Beton'), ('caramida', 'Caramida'), ('lemn', 'Lemn'), ('bca', 'Bca'), ('metal', 'Metal'), ('other', 'Other')], default='beton', max_length=20, verbose_name='Building Type')),
                ('building_construction_date', models.DateTimeField(blank=True, null=True)),
                ('basement', models.BooleanField(default=True)),
                ('potential_rent', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageRenovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=200, null=True)),
                ('renovation_budget', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('date_receiving_money', models.DateTimeField(blank=True)),
                ('date_receiving_key', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageWithTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_rent', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='apartament',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='basement',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='build_sqm',
        ),
        migrations.RemoveField(
            model_name='property',
            name='building',
        ),
        migrations.RemoveField(
            model_name='property',
            name='building_age',
        ),
        migrations.RemoveField(
            model_name='property',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='comfort_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='construction_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='construction_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='property',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='interior_state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='reper',
        ),
        migrations.RemoveField(
            model_name='property',
            name='residence_complex',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.RemoveField(
            model_name='property',
            name='usable_sqm',
        ),
        migrations.RemoveField(
            model_name='property',
            name='vecinatati',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zipcode',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
