# Generated by Django 3.0.7 on 2020-06-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200629_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
