# Generated by Django 3.0.7 on 2020-06-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_10',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_11',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_12',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_9',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_main',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='properties/')),
                ('_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.Property')),
            ],
        ),
    ]
