# Generated by Django 3.0.7 on 2020-07-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200701_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageforrent',
            name='properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_rent', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='stagewithtenant',
            name='properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_tenant', to='properties.Property'),
        ),
    ]
