# Generated by Django 3.0.7 on 2020-07-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200701_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopportunity',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='apartament_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='asking_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='build_sqm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='entrance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='floor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='potential_rent',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='reper',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='residence_complex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='usable_sqm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='vecinatati',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stageopportunity',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
