# Generated by Django 3.0.7 on 2020-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200706_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('account', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenovationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenovationTeamExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('account', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('store', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateTimeField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True)),
                ('company', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
