# Generated by Django 3.0.7 on 2020-07-16 00:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_auto_20200715_2254'),
        ('properties', '0013_monthlymaintenance_renovationteam_renovationteamexpenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='_property',
            new_name='properties',
        ),
        migrations.AddField(
            model_name='monthlymaintenance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlymaintenance',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthlymaintenance',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='renovationteam',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renovationteam',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='renovationteam',
            name='renovation_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.StageRenovation'),
        ),
        migrations.AddField(
            model_name='renovationteamexpenses',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renovationteamexpenses',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stagebuying',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagebuying',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stageforrent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stageforrent',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stageopportunity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stageopportunity',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stagerenovation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagerenovation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stagerenovation',
            name='properties',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
        migrations.AddField(
            model_name='stagewithtenant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagewithtenant',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlymaintenance',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagerenovation',
            name='date_receiving_key',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stagerenovation',
            name='date_receiving_money',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stagerenovation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TenantMonthlyMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('account', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_monthly_expenses', to='tenants.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('renovation_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.RenovationTeam')),
            ],
        ),
        migrations.AddField(
            model_name='renovationteamexpenses',
            name='expense_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.ExpenseTable'),
        ),
    ]
