# Generated by Django 3.0.7 on 2020-07-20 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20200629_1828'),
        ('properties', '0014_auto_20200716_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymaintenance',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='tenantmonthlymaintenance',
            name='tenant',
        ),
        migrations.AddField(
            model_name='expensetable',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensetable',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TenantMonthlyMaintenanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_monthly_maintenance_model', to='contracts.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyMaintenanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_maintenance_model', to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='monthlymaintenance',
            name='monthly_maintenance_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_maintenance', to='properties.MonthlyMaintenanceModel'),
        ),
        migrations.AddField(
            model_name='tenantmonthlymaintenance',
            name='tenant_monthly_maintenance_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_monthly_maintenance', to='properties.TenantMonthlyMaintenanceModel'),
        ),
    ]
