# Generated by Django 3.0.7 on 2020-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20200716_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovationteamexpenses',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='renovationteamexpenses',
            name='store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
