# Generated by Django 3.0.7 on 2020-07-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20200720_1236'),
        ('properties', '0015_auto_20200720_1907'),
    ]

    operations = [
    ]
