# Generated by Django 3.0.7 on 2020-07-25 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20200725_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymaintenance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymaintenance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 25, 22, 40, 33, 263684), null=True),
        ),
    ]
