# Generated by Django 3.0.7 on 2020-07-25 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20200725_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymaintenance',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
