# Generated by Django 3.0.7 on 2020-07-25 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_auto_20200725_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymaintenance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
